### ISSUE TITLE
Having essentially this same issue

### ISSUE THREAD

**Issue by Daowkio** [aydinnyunus/Keylogger#36]
Wanted to make a separate "thread" for this issue instead of crowding the others:

Instance 1 from me: 

Traceback (most recent call last):
  File "C:\Keylogger-master\keylogger.py", line 143, in <module>
    keylogger.run()
  File "C:\Keylogger-master\keylogger.py", line 117, in run
    self.report()
  File "C:\Keylogger-master\keylogger.py", line 80, in report
    self.send_mail(self.email, self.password, "\n\n" + self.log)
  File "C:\Keylogger-master\keylogger.py", line 76, in send_mail
    server.login(email, password)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 432, in docmd
    return self.getreply()
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

Instance 2 from @Boba2601:

Traceback (most recent call last):
  File "/root/Keylogger/keylogger.py", line 124, in <module>
    keylogger.run()
  File "/root/Keylogger/keylogger.py", line 94, in run
    self.report()
  File "/root/Keylogger/keylogger.py", line 57, in report
    self.send_mail(self.email, self.password, "\n\n" + self.log)
  File "/root/Keylogger/keylogger.py", line 51, in send_mail
    server.starttls()
  File "/usr/lib/python3.9/smtplib.py", line 753, in starttls
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.9/smtplib.py", line 605, in ehlo_or_helo_if_needed
    (code, resp) = self.helo()
  File "/usr/lib/python3.9/smtplib.py", line 434, in helo
    (code, msg) = self.getreply()
  File "/usr/lib/python3.9/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

_Originally posted by @Boba2601 in https://github.com/aydinnyunus/Keylogger/issues/7#issuecomment-818231687_

**Comment by PanDabStudios** [comment]
what username and password did you use? I found mine using mailtrap like said in readme.md and going to sandbox>inboxes>my inbox>smtp settings and chose from the integrations dropdown python Django. the host and port are already in the code and not configurable, but the user and password is in the lines 25 & 26, IDK if that helped but I hope so
