### ISSUE TITLE
"NameError: name 'keyboard' is not defined" 😬. what to do?

### ISSUE THREAD

**Issue by charan-24** [aydinnyunus/Keylogger#37]
Getting an Error like this:

    Traceback (most recent call last):
      File "/workspace/Keylogger/keylogger.py", line 144, in <module>
        keylogger.run()
      File "/workspace/Keylogger/keylogger.py", line 116, in run
        keyboard_listener = keyboard.Listener(on_press=self.save_data)
    NameError: name 'keyboard' is not defined
    
  What to do?

**Comment by aydinnyunus** [comment]
can you install requirements.txt and  try again ? I updated the requirements.txt

**Comment by CrippledToenail** [comment]
Same

**Comment by Heyiamslice** [comment]
maybe this could help https://bobbyhadz.com/blog/python-no-module-named-keyboard

**Comment by Reavx** [comment]
> Getting an Error like this:
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/Keylogger/keylogger.py", line 144, in <module>
>     keylogger.run()
>   File "/workspace/Keylogger/keylogger.py", line 116, in run
>     keyboard_listener = keyboard.Listener(on_press=self.save_data)
> NameError: name 'keyboard' is not defined
> ```
> 
> What to do?

hey men what did u do u solve that problem?

**Comment by psusmit** [comment]
On line 116 this error occured, but if we check in import we have Listener so try replacing the line with:
keyboard_listener = Listener(on_press=self.save_data)

**Comment by mikethemelon** [comment]
Maybe bc you doesn't have all the requirements, try to pip install every library is needed by manual

**Comment by lAnviuml** [comment]
I have the same thing
`Traceback (most recent call last):
  File "P:\My Documents\keylogger\Keylogger-master\Keylogger-master\keylogger.py", line 143, in <module>
    keylogger.run()
  File "P:\My Documents\keylogger\Keylogger-master\Keylogger-master\keylogger.py", line 115, in run
    keyboard_listener = Listener(on_press=self.save_data)
                        ^^^^^^^^
NameError: name 'Listener' is not defined`

**Comment by NoamAdept** [comment]
I'm still encountering this issue of having the no keyboard defined :(

**Comment by mohammedmehdio** [comment]
> I'm still encountering this issue of having the no keyboard defined :(

i had the same issue but i just run it as python.exe it works
try to run python.exe kelogger.py

**Comment by Kxsh9** [comment]
> > I'm still encountering this issue of having the no keyboard defined :(
> 
> i had the same issue but i just run it as python.exe it works try to run python.exe kelogger.py

How do you do this?
