### ISSUE TITLE
i am not getting audio, screenshot.i just get text of keystroke

### ISSUE THREAD

**Issue by warisab** [aydinnyunus/Keylogger#7]

**Comment by s3udnawar** [comment]
👌

**Comment by Alireza0x** [comment]
> 
> 
> i am not getting audio, screenshot.i just get text of keystroke

dude, I enter the email and password section and run Python, nothing happened, can you help me?

**Comment by s3udnawar** [comment]
Thank you very much, brother. I am trying to learn because I am new in this field😴😴

**Comment by aydinnyunus** [comment]
> > i am not getting audio, screenshot.i just get text of keystroke
> 
> dude, I enter the email and password section and run Python, nothing happened, can you help me?

is there any error ?

**Comment by aydinnyunus** [comment]
> i am not getting audio, screenshot.i just get text of keystroke

r u install the requirements.txt

**Comment by warisab** [comment]
> > > i am not getting audio, screenshot.i just get text of keystroke
> > 
> > 
> > dude, I enter the email and password section and run Python, nothing happened, can you help me?
> 
> is there any error ?

yes this is error please check i install all the requirements

**Comment by nyawpawgithub** [comment]
Can you help me how to setup this? Thanks

**Comment by Boba2601** [comment]
Hi. Can you help me?
ERRORS:

Traceback (most recent call last):
  File "/root/Keylogger/keylogger.py", line 124, in <module>
    keylogger.run()
  File "/root/Keylogger/keylogger.py", line 94, in run
    self.report()
  File "/root/Keylogger/keylogger.py", line 57, in report
    self.send_mail(self.email, self.password, "\n\n" + self.log)
  File "/root/Keylogger/keylogger.py", line 51, in send_mail
    server.starttls()
  File "/usr/lib/python3.9/smtplib.py", line 753, in starttls
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.9/smtplib.py", line 605, in ehlo_or_helo_if_needed
    (code, resp) = self.helo()
  File "/usr/lib/python3.9/smtplib.py", line 434, in helo
    (code, msg) = self.getreply()
  File "/usr/lib/python3.9/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by AxelBlazer** [comment]
> i am not getting audio, screenshot.i just get text of keystroke

I have the same problem

**Comment by CJSparrow** [comment]
guys, you forgot about the first question, it was `i am not getting audio, screenshot.i just get text of keystroke
#7`, any solutions!

**Comment by CJSparrow** [comment]
it doesn't work anyway after converting to exe

**Comment by aydinnyunus** [comment]
I'll look into it.

**Comment by hackjeez** [comment]
Please some should guide me, I'll pay $50... I'm finding it hard to run it

**Comment by geceqasimabad** [comment]
> Please some should guide me, I'll pay $50... I'm finding it hard to run it

please send email on geceqasimabad@gmail.com; I will do it

**Comment by Boba2601** [comment]
@geceqasimabad what exactly doesn't work for you?

**Comment by hackjeez** [comment]
@geceqasimabad if you can help, chloebella8644@gmail.com I hope to hear from you bro

**Comment by Boba2601** [comment]
@hackjeez 4f9DRtzxAknL37Xf6TuZC6UM

**Comment by JawadPy** [comment]
> Please some should guide me, I'll pay $50... I'm finding it hard to run it 

Bruh, give me 50$ and i'll make for you a new keylogger with any features you want, simply we're lazy to make our own keylogger that's why we using github
